version: '3.8'
services:
    server:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: 'server'
    ports:
      - 3000:4000
    mongo: 
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'